In [1]:
# Data source
# https://www.kaggle.com/c/titanic/data

# References
# http://scikit-learn.org/stable/auto_examples/linear_model/plot_iris_logistic.html

In [2]:
# Modules

import pandas as pd
from sklearn import linear_model, preprocessing

In [3]:
# Process raw data

# Read csv data
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
target = pd.read_csv('gender_submission.csv')

# Get features
# Remove clearly unrelated features such as PassengerId or Name improves accuracy for Decision Tree
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
targets = ['Not Survived', 'Survived']

X = train[features]
y = train['Survived']

x = test[features]
t = target['Survived']

# Encode string values
# http://scikit-learn.org/dev/modules/generated/sklearn.preprocessing.LabelEncoder.html

def label_encode(df, col_names):
    
    les = {}
    
    for col_name in col_names:
    
        le = preprocessing.LabelEncoder()
        le.fit(df[col_name])
        df.loc[:, col_name] = le.transform(df[col_name])
    
        les[col_name] = le
        
        print('Encoded Feature Name: {col_name}'.format(col_name=col_name))
        print('Encoded Feature Classes: {classes}'.format(classes=le.classes_))
    
    return les

# Fill NaN values with string to avoid label encoding issues
# http://stackoverflow.com/questions/36808434/label-encoder-encoding-missing-values

# Try clearly out-of-range value -1.0 for continuous data 'Age'
# http://stackoverflow.com/questions/9365982/missing-values-in-scikits-machine-learning

X['Age'].fillna(-1.0, inplace=True)
X['Embarked'].fillna('None', inplace=True)

x['Age'].fillna(-1.0, inplace=True)
x['Embarked'].fillna('None', inplace=True)
x['Fare'].fillna(-1.0, inplace=True)

col_encodees = ['Sex', 'Embarked']

encoders = label_encode(X, col_encodees)

for col_encodee in col_encodees:
    x[col_encodee] = encoders[col_encodee].transform(x[col_encodee])

/Users/yth/anaconda/envs/101/lib/python3.5/site-packages/pandas/core/generic.py:2862: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)
/Users/yth/anaconda/envs/101/lib/python3.5/site-packages/pandas/core/indexing.py:426: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

Encoded Feature Name: Sex
Encoded Feature Classes: ['female' 'male']
Encoded Feature Name: Embarked
Encoded Feature Classes: ['C' 'None' 'Q' 'S']

/Users/yth/anaconda/envs/101/lib/python3.5/site-packages/ipykernel/__main__.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [4]:
# Show processed data

X

     Pclass  Sex  Age  SibSp  Parch      Fare  Embarked
0         3    1   22      1      0    7.2500         3
1         1    0   38      1      0   71.2833         0
2         3    0   26      0      0    7.9250         3
3         1    0   35      1      0   53.1000         3
4         3    1   35      0      0    8.0500         3
5         3    1   -1      0      0    8.4583         2
6         1    1   54      0      0   51.8625         3
7         3    1    2      3      1   21.0750         3
8         3    0   27      0      2   11.1333         3
9         2    0   14      1      0   30.0708         0
10        3    0    4      1      1   16.7000         3
11        1    0   58      0      0   26.5500         3
12        3    1   20      0      0    8.0500         3
13        3    1   39      1      5   31.2750         3
14        3    0   14      0      0    7.8542         3
15        2    0   55      0      0   16.0000         3
16        3    1    2      4      1   29.1250         2
17        2    1   -1      0      0   13.0000         3
18        3    0   31      1      0   18.0000         3
19        3    0   -1      0      0    7.2250         0
20        2    1   35      0      0   26.0000         3
21        2    1   34      0      0   13.0000         3
22        3    0   15      0      0    8.0292         2
23        1    1   28      0      0   35.5000         3
24        3    0    8      3      1   21.0750         3
25        3    0   38      1      5   31.3875         3
26        3    1   -1      0      0    7.2250         0
27        1    1   19      3      2  263.0000         3
28        3    0   -1      0      0    7.8792         2
29        3    1   -1      0      0    7.8958         3
..      ...  ...  ...    ...    ...       ...       ...
861       2    1   21      1      0   11.5000         3
862       1    0   48      0      0   25.9292         3
863       3    0   -1      8      2   69.5500         3
864       2    1   24      0      0   13.0000         3
865       2    0   42      0      0   13.0000         3
866       2    0   27      1      0   13.8583         0
867       1    1   31      0      0   50.4958         3
868       3    1   -1      0      0    9.5000         3
869       3    1    4      1      1   11.1333         3
870       3    1   26      0      0    7.8958         3
871       1    0   47      1      1   52.5542         3
872       1    1   33      0      0    5.0000         3
873       3    1   47      0      0    9.0000         3
874       2    0   28      1      0   24.0000         0
875       3    0   15      0      0    7.2250         0
876       3    1   20      0      0    9.8458         3
877       3    1   19      0      0    7.8958         3
878       3    1   -1      0      0    7.8958         3
879       1    0   56      0      1   83.1583         0
880       2    0   25      0      1   26.0000         3
881       3    1   33      0      0    7.8958         3
882       3    0   22      0      0   10.5167         3
883       2    1   28      0      0   10.5000         3
884       3    1   25      0      0    7.0500         3
885       3    0   39      0      5   29.1250         2
886       2    1   27      0      0   13.0000         3
887       1    0   19      0      0   30.0000         3
888       3    0   -1      1      2   23.4500         3
889       1    1   26      0      0   30.0000         0
890       3    1   32      0      0    7.7500         2

[891 rows x 7 columns]

In [5]:
# Doc ref: http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
# [C] Setting to 10.0 results in ~7% accurracy increase as compared to default 1.0
# The C parameters defines the error term, higher the value of C may cause overfitting
# [gamma] Setting to 0.01 results in ~10% accurracy increase as compared to default 'auto'
# gamma defines how much influence a single training example has. Higher the value of gamma may cause overfitting
# A good default value for gamma is 0.1, where gamma is often 0 < gamma < 1
# [kernel] more complex kernels performs better than linear kernels
# Using Polynomial(2) achieves 98% accuracy, which out performs 80% accuracy of Radial Basis function
# Polynomial comes with a performance cost

clf = linear_model.LogisticRegression()
clf = clf.fit(X, y)

In [13]:
# Use test data to calculate accuracy

prediction = clf.predict(X)
comparison = prediction == y
accuracy = comparison.value_counts()[True] / comparison.count() * 100
print('Accuracy: {accuracy}%'.format(accuracy=accuracy))

Accuracy: 80.13468013468014%